const countries = [
  {name: 'Afghanistan', slug: 'afghanistan'},
  {name: 'Åland Islands', slug: 'ala-aland-islands'},
  {name: 'Albania', slug: 'albania'},
  {name: 'Algeria', slug: 'algeria'},
  {name: 'American Samoa', slug: 'american-samoa'},
  {name: 'Andorra', slug: 'andorra'},
  {name: 'Angola', slug: 'angola'},
  {name: 'Anguilla', slug: 'anguilla'},
  {name: 'Antarctica', slug: 'antarctica'},
  {name: 'Antigua and Barbuda', slug: 'antigua-and-barbuda'},
  {name: 'Argentina', slug: 'argentina'},
  {name: 'Armenia', slug: 'armenia'},
  {name: 'Aruba', slug: 'aruba'},
  {name: 'Australia', slug: 'australia'},
  {name: 'Austria', slug: 'austria'},
  {name: 'Azerbaijan', slug: 'azerbaijan'},
  {name: 'Bahamas', slug: 'bahamas'},
  {name: 'Bahrain', slug: 'bahrain'},
  {name: 'Bangladesh', slug: 'bangladesh'},
  {name: 'Barbados', slug: 'barbados'},
  {name: 'Belarus', slug: 'belarus'},
  {name: 'Belgium', slug: 'belgium'},
  {name: 'Belize', slug: 'belize'},
  {name: 'Benin', slug: 'benin'},
  {name: 'Bermuda', slug: 'bermuda'},
  {name: 'Bhutan', slug: 'bhutan'},
  {name: 'Bolivia', slug: 'bolivia'},
  {name: 'Bosnia and Herzegovina', slug: 'bosnia-and-herzegovina'},
  {name: 'Botswana', slug: 'botswana'},
  {name: 'Bouvet Island', slug: 'bouvet-island'},
  {name: 'Brazil', slug: 'brazil'},
  {name: 'British Indian Ocean Territory', slug: 'british-indian-ocean-territory'},
  {name: 'British Virgin Islands', slug: 'british-virgin-islands'},
  {name: 'Brunei Darussalam', slug: 'brunei'},
  {name: 'Bulgaria', slug: 'bulgaria'},
  {name: 'Burkina Faso', slug: 'burkina-faso'},
  {name: 'Burundi', slug: 'burundi'},
  {name: 'Cambodia', slug: 'cambodia'},
  {name: 'Cameroon', slug: 'cameroon'},
  {name: 'Canada', slug: 'canada'},
  {name: 'Cape Verde', slug: 'cape-verde'},
  {name: 'Cayman Islands', slug: 'cayman-islands'},
  {name: 'Central African Republic', slug: 'central-african-republic'},
  {name: 'Chad', slug: 'chad'},
  {name: 'Chile', slug: 'chile'},
  {name: 'China', slug: 'china'},
  {name: 'Christmas Island', slug: 'christmas-island'},
  {name: 'Cocos (Keeling) Islands', slug: 'cocos-keeling-islands'},
  {name: 'Colombia', slug: 'colombia'},
  {name: 'Comoros', slug: 'comoros'},
  {name: 'Congo (Brazzaville)', slug: 'congo-brazzaville'},
  {name: 'Congo (Kinshasa)', slug: 'congo-kinshasa'},
  {name: 'Cook Islands', slug: 'cook-islands'},
  {name: 'Costa Rica', slug: 'costa-rica'},
  {name: 'Croatia', slug: 'croatia'},
  {name: 'Cuba', slug: 'cuba'},
  {name: 'Cyprus', slug: 'cyprus'},
  {name: 'Czech Republic', slug: 'czech-republic'},
  {name: 'Côte d\'Ivoire', slug: 'cote-divoire'},
  {name: 'Denmark', slug: 'denmark'},
  {name: 'Djibouti', slug: 'djibouti'},
  {name: 'Dominica', slug: 'dominica'},
  {name: 'Dominican Republic', slug: 'dominican-republic'},
  {name: 'Ecuador', slug: 'ecuador'},
  {name: 'Egypt', slug: 'egypt'},
  {name: 'El Salvador', slug: 'el-salvador'},
  {name: 'Equatorial Guinea', slug: 'equatorial-guinea'},
  {name: 'Eritrea', slug: 'eritrea'},
  {name: 'Estonia', slug: 'estonia'},
  {name: 'Ethiopia', slug: 'ethiopia'},
  {name: 'Falkland Islands (Malvinas)', slug: 'falkland-islands-malvinas'},
  {name: 'Faroe Islands', slug: 'faroe-islands'},
  {name: 'Fiji', slug: 'fiji'},
  {name: 'Finland', slug: 'finland'},
  {name: 'France', slug: 'france'},
  {name: 'French Guiana', slug: 'french-guiana'},
  {name: 'French Polynesia', slug: 'french-polynesia'},
  {name: 'French Southern Territories', slug: 'french-southern-territories'},
  {name: 'Gabon', slug: 'gabon'},
  {name: 'Gambia', slug: 'gambia'},
  {name: 'Georgia', slug: 'georgia'},
  {name: 'Germany', slug: 'germany'},
  {name: 'Ghana', slug: 'ghana'},
  {name: 'Gibraltar', slug: 'gibraltar'},
  {name: 'Greece', slug: 'greece'},
  {name: 'Greenland', slug: 'greenland'},
  {name: 'Grenada', slug: 'grenada'},
  {name: 'Guadeloupe', slug: 'guadeloupe'},
  {name: 'Guam', slug: 'guam'},
  {name: 'Guatemala', slug: 'guatemala'},
  {name: 'Guernsey', slug: 'guernsey'},
  {name: 'Guinea', slug: 'guinea'},
  {name: 'Guinea-Bissau', slug: 'guinea-bissau'},
  {name: 'Guyana', slug: 'guyana'},
  {name: 'Haiti', slug: 'haiti'},
  {name: 'Heard and Mcdonald Islands', slug: 'heard-and-mcdonald-islands'},
  {name: 'Holy See (Vatican City State)', slug: 'holy-see-vatican-city-state'},
  {name: 'Honduras', slug: 'honduras'},
  {name: 'Hong Kong, SAR China', slug: 'hong-kong-sar-china'},
  {name: 'Hungary', slug: 'hungary'},
  {name: 'Iceland', slug: 'iceland'},
  {name: 'India', slug: 'india'},
  {name: 'Indonesia', slug: 'indonesia'},
  {name: 'Iran, Islamic Republic of', slug: 'iran'},
  {name: 'Iraq', slug: 'iraq'},
  {name: 'Ireland', slug: 'ireland'},
  {name: 'Isle of Man', slug: 'isle-of-man'},
  {name: 'Israel', slug: 'israel'},
  {name: 'Italy', slug: 'italy'},
  {name: 'Jamaica', slug: 'jamaica'},
  {name: 'Japan', slug: 'japan'},
  {name: 'Jersey', slug: 'jersey'},
  {name: 'Jordan', slug: 'jordan'},
  {name: 'Kazakhstan', slug: 'kazakhstan'},
  {name: 'Kenya', slug: 'kenya'},
  {name: 'Kiribati', slug: 'kiribati'},
  {name: 'Korea (North)', slug: 'korea-north'},
  {name: 'Korea (South)', slug: 'korea-south'},
  {name: 'Kuwait', slug: 'kuwait'},
  {name: 'Kyrgyzstan', slug: 'kyrgyzstan'},
  {name: 'Lao PDR', slug: 'lao-pdr'},
  {name: 'Latvia', slug: 'latvia'},
  {name: 'Lebanon', slug: 'lebanon'},
  {name: 'Lesotho', slug: 'lesotho'},
  {name: 'Liberia', slug: 'liberia'},
  {name: 'Libya', slug: 'libya'},
  {name: 'Liechtenstein', slug: 'liechtenstein'},
  {name: 'Lithuania', slug: 'lithuania'},
  {name: 'Luxembourg', slug: 'luxembourg'},
  {name: 'Macao, SAR China', slug: 'macao-sar-china'},
  {name: 'Macedonia, Republic of', slug: 'macedonia'},
  {name: 'Madagascar', slug: 'madagascar'},
  {name: 'Malawi', slug: 'malawi'},
  {name: 'Malaysia', slug: 'malaysia'},
  {name: 'Maldives', slug: 'maldives'},
  {name: 'Mali', slug: 'mali'},
  {name: 'Malta', slug: 'malta'},
  {name: 'Marshall Islands', slug: 'marshall-islands'},
  {name: 'Martinique', slug: 'martinique'},
  {name: 'Mauritania', slug: 'mauritania'},
  {name: 'Mauritius', slug: 'mauritius'},
  {name: 'Mayotte', slug: 'mayotte'},
  {name: 'Mexico', slug: 'mexico'},
  {name: 'Micronesia, Federated States of', slug: 'micronesia'},
  {name: 'Moldova', slug: 'moldova'},
  {name: 'Monaco', slug: 'monaco'},
  {name: 'Mongolia', slug: 'mongolia'},
  {name: 'Montenegro', slug: 'montenegro'},
  {name: 'Montserrat', slug: 'montserrat'},
  {name: 'Morocco', slug: 'morocco'},
  {name: 'Mozambique', slug: 'mozambique'},
  {name: 'Myanmar', slug: 'myanmar'},
  {name: 'Namibia', slug: 'namibia'},
  {name: 'Nauru', slug: 'nauru'},
  {name: 'Nepal', slug: 'nepal'},
  {name: 'Netherlands', slug: 'netherlands'},
  {name: 'Netherlands Antilles', slug: 'netherlands-antilles'},
  {name: 'New Caledonia', slug: 'new-caledonia'},
  {name: 'New Zealand', slug: 'new-zealand'},
  {name: 'Nicaragua', slug: 'nicaragua'},
  {name: 'Niger', slug: 'niger'},
  {name: 'Nigeria', slug: 'nigeria'},
  {name: 'Niue', slug: 'niue'},
  {name: 'Norfolk Island', slug: 'norfolk-island'},
  {name: 'Northern Mariana Islands', slug: 'northern-mariana-islands'},
  {name: 'Norway', slug: 'norway'},
  {name: 'Oman', slug: 'oman'},
  {name: 'Pakistan', slug: 'pakistan'},
  {name: 'Palau', slug: 'palau'},
  {name: 'Palestinian Territory', slug: 'palestine'},
  {name: 'Panama', slug: 'panama'},
  {name: 'Papua New Guinea', slug: 'papua-new-guinea'},
  {name: 'Paraguay', slug: 'paraguay'},
  {name: 'Peru', slug: 'peru'},
  {name: 'Philippines', slug: 'philippines'},
  {name: 'Pitcairn', slug: 'pitcairn'},
  {name: 'Poland', slug: 'poland'},
  {name: 'Portugal', slug: 'portugal'},
  {name: 'Puerto Rico', slug: 'puerto-rico'},
  {name: 'Qatar', slug: 'qatar'},
  {name: 'Republic of Kosovo', slug: 'kosovo'},
  {name: 'Romania', slug: 'romania'},
  {name: 'Russian Federation', slug: 'russia'},
  {name: 'Rwanda', slug: 'rwanda'},
  {name: 'Réunion', slug: 'réunion'},
  {name: 'Saint Helena', slug: 'saint-helena'},
  {name: 'Saint Kitts and Nevis', slug: 'saint-kitts-and-nevis'},
  {name: 'Saint Lucia', slug: 'saint-lucia'},
  {name: 'Saint Pierre and Miquelon', slug: 'saint-pierre-and-miquelon'},
  {name: 'Saint Vincent and Grenadines', slug: 'saint-vincent-and-the-grenadines'},
  {name: 'Saint-Barthélemy', slug: 'saint-barthélemy'},
  {name: 'Saint-Martin (French part)', slug: 'saint-martin-french-part'},
  {name: 'Samoa', slug: 'samoa'},
  {name: 'San Marino', slug: 'san-marino'},
  {name: 'Sao Tome and Principe', slug: 'sao-tome-and-principe'},
  {name: 'Saudi Arabia', slug: 'saudi-arabia'},
  {name: 'Senegal', slug: 'senegal'},
  {name: 'Serbia', slug: 'serbia'},
  {name: 'Seychelles', slug: 'seychelles'},
  {name: 'Sierra Leone', slug: 'sierra-leone'},
  {name: 'Singapore', slug: 'singapore'},
  {name: 'Slovakia', slug: 'slovakia'},
  {name: 'Slovenia', slug: 'slovenia'},
  {name: 'Solomon Islands', slug: 'solomon-islands'},
  {name: 'Somalia', slug: 'somalia'},
  {name: 'South Africa', slug: 'south-africa'},
  {name: 'South Georgia and the South Sandwich Islands', slug: 'south-georgia-and-the-south-sandwich-islands'},
  {name: 'South Sudan', slug: 'south-sudan'},
  {name: 'Spain', slug: 'spain'},
  {name: 'Sri Lanka', slug: 'sri-lanka'},
  {name: 'Sudan', slug: 'sudan'},
  {name: 'Suriname', slug: 'suriname'},
  {name: 'Svalbard and Jan Mayen Islands', slug: 'svalbard-and-jan-mayen-islands'},
  {name: 'Swaziland', slug: 'swaziland'},
  {name: 'Sweden', slug: 'sweden'},
  {name: 'Switzerland', slug: 'switzerland'},
  {name: 'Syrian Arab Republic (Syria)', slug: 'syria'},
  {name: 'Taiwan, Republic of China', slug: 'taiwan'},
  {name: 'Tajikistan', slug: 'tajikistan'},
  {name: 'Tanzania, United Republic of', slug: 'tanzania'},
  {name: 'Thailand', slug: 'thailand'},
  {name: 'Timor-Leste', slug: 'timor-leste'},
  {name: 'Togo', slug: 'togo'},
  {name: 'Tokelau', slug: 'tokelau'},
  {name: 'Tonga', slug: 'tonga'},
  {name: 'Trinidad and Tobago', slug: 'trinidad-and-tobago'},
  {name: 'Tunisia', slug: 'tunisia'},
  {name: 'Turkey', slug: 'turkey'},
  {name: 'Turkmenistan', slug: 'turkmenistan'},
  {name: 'Turks and Caicos Islands', slug: 'turks-and-caicos-islands'},
  {name: 'Tuvalu', slug: 'tuvalu'},
  {name: 'US Minor Outlying Islands', slug: 'us-minor-outlying-islands'},
  {name: 'Uganda', slug: 'uganda'},
  {name: 'Ukraine', slug: 'ukraine'},
  {name: 'United Arab Emirates', slug: 'united-arab-emirates'},
  {name: 'United Kingdom', slug: 'united-kingdom'},
  {name: 'United States of America', slug: 'united-states'},
  {name: 'Uruguay', slug: 'uruguay'},
  {name: 'Uzbekistan', slug: 'uzbekistan'},
  {name: 'Vanuatu', slug: 'vanuatu'},
  {name: 'Venezuela (Bolivarian Republic)', slug: 'venezuela'},
  {name: 'Viet Nam', slug: 'vietnam'},
  {name: 'Virgin Islands, US', slug: 'virgin-islands'},
  {name: 'Wallis and Futuna Islands', slug: 'wallis-and-futuna-islands'},
  {name: 'Western Sahara', slug: 'western-sahara'},
  {name: 'Yemen', slug: 'yemen'},
  {name: 'Zambia', slug: 'zambia'},
  {name: 'Zimbabwe', slug: 'zimbabwe'}
];
